name: .NET Core CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest # or windows-latest

        steps:
            - uses: actions/checkout@v4 # Check out the code

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0.x" # Specify .NET version

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal

            - name: Check for secrets
              run: |
                  if grep -r "client_secret" ./src/; then
                    echo "ðŸš¨ Secrets detected in code!" && exit 1
                  fi
